addons:
ssh_known_hosts:
- 39.99.128.226
before_install:
- openssl aes-256-cbc -K $encrypted_9b2d7e19d83c_key -iv $encrypted_9b2d7e19d83c_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
script:
- ssh root@39.99.128.226 -o StrictHostKeyChecking=no 'cd /root/front-end && git pull && rm -rf ./dist && npm run build && cp -rf dist/ /root/nginx/ && cd /root/nginx
  && docker-compose stop && docker-compose up -d'
